DELETE FROM materialsin; 
INSERT INTO materialsin (numero, palabra, imagenPath) VALUES (0, 'OSO', 'cero.jpg');
INSERT INTO materialsin (numero, palabra, imagenPath) VALUES (1, 'TE', 'uno.jpg');
INSERT INTO materialsin (numero, palabra, imagenPath) VALUES (2, 'ÑU', 'dos.png');
INSERT INTO materialsin (numero, palabra, imagenPath) VALUES (3, 'HUMO', 'tres.png');
INSERT INTO materialsin (numero, palabra, imagenPath) VALUES (4, 'ORO', 'cuatro.png');
INSERT INTO materialsin (numero, palabra, imagenPath) VALUES (5, 'OLA', 'cinco.png');
INSERT INTO materialsin (numero, palabra, imagenPath) VALUES (6, 'OJO', 'seis.png');
INSERT INTO materialsin (numero, palabra, imagenPath) VALUES (7, 'OCA', 'siete.png');
INSERT INTO materialsin (numero, palabra, imagenPath) VALUES (8, 'VIA', 'ocho.png');
INSERT INTO materialsin (numero, palabra, imagenPath) VALUES (9, 'BUHO', 'nueve.png');
