DELETE FROM tarjetamemoria; 
INSERT INTO tarjetamemoria (numero, palabra, imagen) VALUES (0, 'OSO', 'cero.jpg');
INSERT INTO tarjetamemoria (numero, palabra, imagen) VALUES (1, 'TE', 'uno.jpg');
INSERT INTO tarjetamemoria (numero, palabra, imagen) VALUES (2, 'NU', 'dos.png');
INSERT INTO tarjetamemoria (numero, palabra, imagen) VALUES (3, 'HUMO', 'tres.png');
INSERT INTO tarjetamemoria (numero, palabra, imagen) VALUES (4, 'ORO', 'cuatro.png');
INSERT INTO tarjetamemoria (numero, palabra, imagen) VALUES (5, 'OLA', 'cinco.png');
INSERT INTO tarjetamemoria (numero, palabra, imagen) VALUES (6, 'OJO', 'seis.png');
INSERT INTO tarjetamemoria (numero, palabra, imagen) VALUES (7, 'OCA', 'siete.png');
INSERT INTO tarjetamemoria (numero, palabra, imagen) VALUES (8, 'VIA', 'ocho.png');
INSERT INTO tarjetamemoria (numero, palabra, imagen) VALUES (9, 'BUHO', 'nueve.png');
